site_name: Renault PR-830
site_url: https://thmahe.github.io/PR-830

theme:
  logo: assets/logo.png
  name: material
  palette:
    primary: amber
  favicon: assets/favicon.png

markdown_extensions:
  - tables
  - attr_list

plugins:
   - search:
       separator: '[\s]+'
   - i18n:
       default_language: fr
       languages:
         en: English
         fr: Français
#         de: Dutch

extra_css:
  - assets/css/custom.css

nav:
- 'index.md'
- 'parts/index.md'
