site_name: Renault PR-830
site_url: https://thmahe.github.io/PR-830
repo_url: https://github.com/thmahe/PR-830
repo_name: thmahe/PR-830

theme:
  logo: assets/logo.png
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: amber
  favicon: assets/favicon.png
  custom_dir: overrides

markdown_extensions:
  - tables
  - attr_list

plugins:
   - search:
       separator: '[\s]+'
   - i18n:
       default_language: fr
       languages:
         en: English
         fr: Français
#         de: Dutch

extra_css:
  - assets/css/custom.css

extra:
  analytics:
    provider: custom
    property: G-B5CJW73D7C
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
nav:
- 'index.md'
- 'parts/index.md'
